"""İlk Revizyon

Revision ID: 2f6e1e52f797
Revises: 
Create Date: 2024-12-18 20:46:10.470224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6e1e52f797'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ogretmen',
    sa.Column('adi', sa.String(length=255), nullable=False),
    sa.Column('soyadi', sa.String(length=255), nullable=False),
    sa.Column('tel_no', sa.String(length=10), nullable=False),
    sa.Column('cinsiyet', sa.String(length=1), nullable=False),
    sa.Column('dogum_tarihi', sa.DateTime(), nullable=False),
    sa.Column('brans', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_zaman', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ogretmen_adi'), 'ogretmen', ['adi'], unique=False)
    op.create_index(op.f('ix_ogretmen_brans'), 'ogretmen', ['brans'], unique=False)
    op.create_index(op.f('ix_ogretmen_cinsiyet'), 'ogretmen', ['cinsiyet'], unique=False)
    op.create_index(op.f('ix_ogretmen_soyadi'), 'ogretmen', ['soyadi'], unique=False)
    op.create_index(op.f('ix_ogretmen_tel_no'), 'ogretmen', ['tel_no'], unique=False)
    op.create_table('veli',
    sa.Column('adi', sa.String(length=255), nullable=False),
    sa.Column('soyadi', sa.String(length=255), nullable=False),
    sa.Column('tel_no', sa.String(length=10), nullable=False),
    sa.Column('cinsiyet', sa.String(length=1), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_zaman', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veli_adi'), 'veli', ['adi'], unique=False)
    op.create_index(op.f('ix_veli_cinsiyet'), 'veli', ['cinsiyet'], unique=False)
    op.create_index(op.f('ix_veli_soyadi'), 'veli', ['soyadi'], unique=False)
    op.create_index(op.f('ix_veli_tel_no'), 'veli', ['tel_no'], unique=False)
    op.create_table('ders',
    sa.Column('adi', sa.String(length=255), nullable=False),
    sa.Column('ogretmen_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_zaman', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ogretmen_id'], ['ogretmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ders_adi'), 'ders', ['adi'], unique=False)
    op.create_table('sinif',
    sa.Column('kacinci_sinif', sa.String(length=5), nullable=False),
    sa.Column('sube', sa.String(length=5), nullable=False),
    sa.Column('ogretmen_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_zaman', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ogretmen_id'], ['ogretmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sinif_kacinci_sinif'), 'sinif', ['kacinci_sinif'], unique=False)
    op.create_index(op.f('ix_sinif_sube'), 'sinif', ['sube'], unique=False)
    op.create_table('ogrenci',
    sa.Column('tc_no', sa.String(length=11), nullable=False),
    sa.Column('adi', sa.String(length=255), nullable=False),
    sa.Column('soyadi', sa.String(length=255), nullable=False),
    sa.Column('numara', sa.String(length=11), nullable=False),
    sa.Column('cinsiyet', sa.String(length=1), nullable=False),
    sa.Column('dogum_tarihi', sa.DateTime(), nullable=False),
    sa.Column('veli_id', sa.Uuid(), nullable=False),
    sa.Column('sinif_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_zaman', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sinif_id'], ['sinif.id'], ),
    sa.ForeignKeyConstraint(['veli_id'], ['veli.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ogrenci_adi'), 'ogrenci', ['adi'], unique=False)
    op.create_index(op.f('ix_ogrenci_cinsiyet'), 'ogrenci', ['cinsiyet'], unique=False)
    op.create_index(op.f('ix_ogrenci_numara'), 'ogrenci', ['numara'], unique=False)
    op.create_index(op.f('ix_ogrenci_soyadi'), 'ogrenci', ['soyadi'], unique=False)
    op.create_index(op.f('ix_ogrenci_tc_no'), 'ogrenci', ['tc_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ogrenci_tc_no'), table_name='ogrenci')
    op.drop_index(op.f('ix_ogrenci_soyadi'), table_name='ogrenci')
    op.drop_index(op.f('ix_ogrenci_numara'), table_name='ogrenci')
    op.drop_index(op.f('ix_ogrenci_cinsiyet'), table_name='ogrenci')
    op.drop_index(op.f('ix_ogrenci_adi'), table_name='ogrenci')
    op.drop_table('ogrenci')
    op.drop_index(op.f('ix_sinif_sube'), table_name='sinif')
    op.drop_index(op.f('ix_sinif_kacinci_sinif'), table_name='sinif')
    op.drop_table('sinif')
    op.drop_index(op.f('ix_ders_adi'), table_name='ders')
    op.drop_table('ders')
    op.drop_index(op.f('ix_veli_tel_no'), table_name='veli')
    op.drop_index(op.f('ix_veli_soyadi'), table_name='veli')
    op.drop_index(op.f('ix_veli_cinsiyet'), table_name='veli')
    op.drop_index(op.f('ix_veli_adi'), table_name='veli')
    op.drop_table('veli')
    op.drop_index(op.f('ix_ogretmen_tel_no'), table_name='ogretmen')
    op.drop_index(op.f('ix_ogretmen_soyadi'), table_name='ogretmen')
    op.drop_index(op.f('ix_ogretmen_cinsiyet'), table_name='ogretmen')
    op.drop_index(op.f('ix_ogretmen_brans'), table_name='ogretmen')
    op.drop_index(op.f('ix_ogretmen_adi'), table_name='ogretmen')
    op.drop_table('ogretmen')
    # ### end Alembic commands ###
